### ISSUE TITLE
interop with roxigen

### ISSUE THREAD

**Issue by piccolbo** [RevolutionAnalytics/quickcheck#30]
is it possible to define a test roclet? On a suggestion by @ctbrown

**Comment by piccolbo** [comment]
Little weary of becoming dependent on roxygen, nor it's clear how to add roclets and get them supported. The function-centric view of roxygen is only one possible point of view on code (I may want to see all the functions together, or all the tests together) and a many-to-one relation between tests and functions is the only one that could be added naturally (see for instance the acrobatic work that needs to be done to document one argument once for many functions, and the ugliness of the results). So I am leaning against this one. We need a way to associate functions and tests, it needs to be many-to-many, it has to be documentation-agnostic. If someone then wants to create a roclet based on that, great.

**Comment by ctbrown** [comment]
* In case we are talking about different things, the suggestion was to use roxygen but roxygen2. [https://github.com/klutometis/roxygen]; There is a difference.  

* There is also a Roxygen3 project that is rewriting roxygen2 and suggests that it will be merged (or has been merged) back into Roxygen 2. 

* I think that writing roclets is fairly straight-forward: cf. [https://github.com/klutometis/roxygen/blob/master/R/roclet-rd.R]. It is pretty easy to follow what is going on.

* To get a special roclet supported, my guess is to include the roclet in the `quickcheck` package.  It maybe easy to get everything playing nice together since quickcheck would have to be loaded to do anything with this roclet.

* With respect to your many-to-many case, I agree that this is likely needed, however, the "function-centric" view covers about 90% of the use cases. Most development would not need anything more.  Nothing about creating a roclet precludes additional tests (files) to support the many-to-many case, the systems checking, the bench-marking, integration tests, etc.

Two thoughts:
1. This issue is related to RStudio not having the ability to edit code along side the tests. This may be a feature in an upcoming release of R-Studio.  ( We can't have been the only ones pining for this feature ).  This should be checked.

2. It might be easier and more useful/easirer to create a `@test` roclet, that will deploy tests to testthat, testit, RUnit, quickcheck or whichever the testing package used is.  Probably nothing that you want to support under this project however.

**Comment by piccolbo** [comment]
One counterexample to function at-a-time spec are RHadoop tests. Many tests check that f is the inverse of g. Serialization and deserialization, any number of formats, read and write to disk etc. Another type of test is the "backend equivalence test" whereby one tries to do a computation locally and on a cluster expecting the same results. In the first case we are testing two functions in one test, in the second two methods of one generic. Agreed on all your other points. Ultimately, this doesn't belong here because quickcheck should not be coupled with any documentation system.

**Comment by ctbrown** [comment]
I came to the same conclusion.  I think there is some other
testing/documentation packages that should support multiple testing
backends. Quickcheck is not that.
